### ISSUE TITLE
Not able to edit after forking

### ISSUE THREAD

**Issue by Vishesh987** [DivSriv/Armageddon#1]
Hi, I forked this repo, I have it in my github now but I can't click any buttons and track my progress. 
I am new to github, kindly help

**Comment by DivSriv** [comment]
Actually, these are not buttons,  these are https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists

And to make changes, you have to click the pencil icon, then change it according to documentation.

Basically you have to change the "x" sign in the task list.

**Comment by Vishesh987** [comment]
> Actually, these are not buttons, these are https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#task-lists
> 
> And to make changes, you have to click the pencil icon, then change it according to documentation.
> 
> Basically you have to change the "x" sign in the task list.


Oh! Thank You for explaining. I didn't know that. 
Is there a way to uncheck all at once?
Edit: I used a text editor and used find and replace to uncheck all at once. Thanks!

**Comment by DivSriv** [comment]
Great ! Yeah you can use IDE and Find and replace at once.
